language: node_js
node_js:
  - '6'
  - '7'
install:
  - NODE_ENV=development npm install
script:
  - npm run lint
  - npm run test
  - npm run coverage-report
after_success:
  - npm run coverage-ci
deploy:
  provider: npm
  email: me@benjaminjt.com
  api_key:
    secure: Jr79pjPwnxc845KSNfMQSwIFquyso0zcG9LQIJGmmM3p+BTtm/dX0k5YgYiUPzPUZFejyJ/OsTIiE/NPa6PCK5j4cGdN17N68m+xYsP0yNcEaPgtmiwDiR3BgqLq2HdhgaKbbqrBFG9/wdtBTPLhOfATFHAkQClTtfAbVOGI9yUSjVQgFNy3LERhoq9NlYz2S0h7Yc2KrtqDJ5mz/CFaMsc7EcbLuHL/A8xo2ytIV2DocxZWnyKoEf/1+giPJ4TfvOd/3c/XXY6+Ms/wPbwfeZOZiavU1LCqIZ6EXLMb6/lgspOl1bRSiNm6cmXY3YqfCYJGzO67PGr+RR1LY30Ws4cMain3k+8QV9vXUjib/mBNqvn63MEGGM5anXIjaUlZ+cQai9HKprtG2oWcDbuVX/TOfYPlVX8MtRkG20R6AUn91wjtCcDT+FNh89yxYNSa87m7HDdiQisntLkCpE6wW88Uvnl7sDFdSlq+L76rj1E9ikglZsnHcGjmlJJWen49cXWzsv74PiB9TTS9O9LT4LltyuTFA3IanEZjEBEVFNef9spyxqKcFzJ4FuxrJOtP7vQa1HdKulnswPcbGYhMzWExjmuW+nFzR4aPJx4VUO2615AVV7tROOcfhypM3l66LvMEghd/Wk9upAk61OiJNst3dI0UVv9jFsgfERVPu9k=
  on:
    tags: true
    repo: benjaminjt/micro-nervous
