language: node_js
node_js:
  - '6'
  - '7'
install:
  - NODE_ENV=development npm install
script:
  - npm run lint
  - npm run test
  - npm run coverage-report
after_success:
  - npm run coverage-ci
deploy:
  provider: npm
  email: me@benjaminjt.com
  api_key:
    secure: d56OiXcltpmKPtU86fAifrHOOQvk0iGWlK+YBVd+gGYTc5ncSBBnfW1dVJgzyql+pjWF3cp8yPmrniZ9o9CZE2eQbIJraVRNia3JqRKDKmPkKqngt8bnYrI+pkp2Y34L7285DQ2eSN6kyj+6L0LaLou0lT8lykMnzN9ru/oijhmHI/FVH2CipxdpR8i8agzDNGlgkCL7ANAdIU1fjercBP9m4iFeKJ/WFelQSR9hN8EADrxhZ6BRaC0LpjCjqQoN1MzNusxj8KGubG2kih6mZ4rqb7KKBSy1W64p7q/d4z9cq+77xyyEzdwsYsZOkzZlIY1Fqhd2OuexImDEzcg2zAZBOM26pzoeiYkUZFDsoy0lrXFryDZr1iC/nlfJihddIRCQMN+MelxQb1Q62hqVhqvJ12PHVIpOKgM1mGTAbjHe7fzJ/dGOqJXcedoEniJNhlfzFDWAx2kyEvXGzoVSwEZfpzqRVGAwRMNN5wkuELHxqYgsyL2gwOpPdD28VqI+rkF8EV3woIn0oNpfmavbBL+WMSQbhlfhn26xe9tlMnowYyMznVuNGICvHpOod7+uozIpSmCe9XhNYBsOJAunRxYPOzzoxQJmv5tTRDV7xR+AIP+s3GsnoPkgLM6gdYaZRchoqPCVMrWLAN5sPBo1KRclJqPuWHUGG2jWRlD5+iE=
  on:
    tags: true
    repo: benjaminjt/micro-nervous
